[[redirects]]
  from = "/*"
  to = '/index.html'
  status = 200

[[redirects]]
  from = "/src/*"
  to = '/src/:splat'
  status = 200

[[redirects]]
  from = "/modules/*"
  to = '/modules/:splat'
  status = 200
